server: # REST server
  port: 27015
  address: 192.168.1.250
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "xd"
    ws:
      port: 27015
      host: 192.168.1.250
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 600
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
